---
- name: deploy and start apache server
  hosts: all
  vars:
      apache_package: httpd
      firewall_package: firewalld
      wev_service: httpd
      firewall_service: firewalld
      rule: http
  tasks: 
      - name: install and update latest packages
        yum: 
            name:
                - "{{ apache_package }}"
                - "{{ firewall_package }}"
            state: latest
      - name: start and enable {{ firewall_service }}
        service:
            name: "{{ firewall_service }}"
            enabled: true
            state: started
      - name: create web content
        copy: 
            content: "Welcome to my super duper web page!"
            dest: /var/www/html/index.html
            
      - name: enable start and enable web service
        service: 
            name: "{{ web_service }}"
            enabled: true
            state: started
      - name: create rule http
        firewalld:
            service: "{{ rule }}"
            permanent: true
            immediate: true
            state: enabled

- name: verify the web server
  hosts: localhost
  become: false
  tasks:
      - name: test that webserver is available
        uri:
            url: http://ansible2.example.com
            status_code: 200
            
            
                 