---
- name: Chapter 1
  hosts: all
  tasks: 
   - name: install nginx
      apt: name=nginx
   - name: install config files
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.onf
      notify: notify nginx
   - name: add user
      user: name=deploy group=web
  
  handlers: 
   - name: notify nginx
      service: name=nginx state=restarted
   