---
- name: Deploy and update apache webserver
  hosts: centos-webserver.example.com
  vars: 
      httpd_package: httpd
      firewall_package: firewalld
      httpd_service: httpd
      firewalld_service: firewalld
      web_rule: http
      index_content: "hello to my super duper web site ;)"
  tasks:
      - name: install apache webserver
        yum:
            name:
                - "{{ httpd_package }}"
                - "{{firewall_package}}"
            state: latest
      - name: enable and start firewalld
        yum:
            name: "{{ firewall_package }}"
            enabled: true
            state: started
      - name: create index.html
        copy:
            content: "{{ httpd_package }}"
            dest: /var/www/html/index.html
      - name: install apache webserver
        yum:
            name: "{{ httpd_package }}"
            enabled: true
            state: started
      - name: create http rule
        firewalld:
            service: "{{ web_rule }}"
            permanent: true
            immediate: true
            state: enabled