---
- name: deploy and starg Apache
  hosts: all
  include_vars: vars/{{ ansible_os_family }}.yml
  
  tasks:
    - name: install abd update latest packages
      package: 
        name: 
          - "{{ web_package }} "
          - "{{ firewall_package }} "
          - "{{ ftp_package }} "
          - "{{ db_package }} "
        state: latest
      notify: 
        - success
    - name: start and enabled {{ firewall_service }}
      service: 
        name: " {{ firewall_service }} "
        state: started
        enabled: true
    
    - name: start anme enable {{ web_service }}
      service:
        name: "{{ web_service }}"
        enabled: yes
        state: started
    
    - include_tasks: ubuntu.yml
      when: ansible_os_family == 'Ubuntu'
    
    - include_tasks: redhat.yml
      when: ansible_os_family == 'RedHat'
    
  handlers: 
    - name: success
      msg: package installation on {{ inventory_hostname }} successful
      