- name: Provision a vagrant machine 
  hosts: localhost
  vars: 
    box: trusty64
  tasks:
   - name: create a Vagrantfile
     command: vagrant init {{ box }} creates=Vagrantfile

   - name: bring up vagrant machine
     command: vagrant up
   
   - name: add vagrant machine to inventory
     add_host: > 
        name=vagrant
        ansible_host=127.0.0.1
        ansible_port=2222
        ansible_user=vagrant
        ansible_private_key_file=~/.vagrant.d/insecure_private_key

- name: do something with vagrant machine
  hosts: vagrant
  become: yes
  tasks: 
     # shomething!!