---
- name: manage users ang groups membership
  hosts: all
  tasks:
   - name: create user and add to groups
     user:
       name: "{{ item.name }}"
       state: present
       groups: "{{ item.group }}"
     with_item:
       - { name: 'linda', group: 'studens' }
       - { name: 'anna', group: 'profs' }