---
- name: vars with nested loops playbook
  hosts: all
  vars: 
   myusers:
     - linda
     - anna
   mygroups:
     - students
     - profs
  tasts:
   - name: create groups
     group: 
       name: "{{ item }}"
       state: present
     with_items: "{{ mygroups }}"
   - name: create users
     user:
       name: "{{ item[0] }}"
       state: present
       groups: "{{ item[1] }}"
     with_nested:
       - "{{ myusers }}"
       - "{{ mygroups }}"