---
- name: copy new index.html
  hosts: all
  tasks:
     - name: install httpd
       yum: name=httpd
     - name: start httpd
       service: httpd
       state: started
  tasks:
     - name: copy index.html
       copy:
         src: /tmp/index.html
         dest: /ver/www/html/index.html
       notify: 
         - restart_web
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
...