---
- name: clean up all
  hosts: all
  tasks:
  - name: remove services
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - httpd
      - vsftpd
  - name: remove files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/ansible/fact.d
      - /etc/ansible/hosts